# Generated by Django 3.0 on 2021-12-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20211206_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('Pobreza', 'Pobreza'), ('Hambre', 'Hambre'), ('Salud', 'Salud'), ('Educación', 'Educación'), ('Igualdad de Género', 'Igualdad de Género'), ('Agua', 'Agua'), ('Energía', 'Energía'), ('Economía', 'Economía'), ('Infraestructura', 'Infraestructura'), ('Desigualdad', 'Desigualdad'), ('Ciudades', 'Ciudades'), ('Consumo', 'Consumo'), ('Cambio Climatico', 'Cambio Climatico'), ('Océanos', 'Océanos'), ('Biodiversidad', 'Biodiversidad'), ('Paz - Justicia ', 'Paz - Justicia '), ('Aliazas', 'Aliazas')], default='Pobreza', max_length=40),
        ),
    ]
